# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r: bioc-release

# for codecov
r_packages:
  - covr

# only report coverage after build is successful
after_success:
  - travis_wait Rscript -e 'covr::codecov()'
